/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kenjic_dusan_chatapplication_Cryptography */

#ifndef _Included_kenjic_dusan_chatapplication_Cryptography
#define _Included_kenjic_dusan_chatapplication_Cryptography
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kenjic_dusan_chatapplication_Cryptography
 * Method:    cryptography
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kenjic_dusan_chatapplication_Cryptography_cryptography
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
